name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'env'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 登录到 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
        
    - uses: actions/checkout@v3
    - name: 构建Docker image（kubetools）
      run: |
        cd kubetools && cat env &&source env 
        docker build -t docker.io/corray/$SERVERNAME:$VERSION .
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/$SERVERNAME:$VERSION
        docker tag docker.io/${{ secrets.DOCKER_USERNAME }}/$SERVERNAME:$VERSION docker.io/${{ secrets.DOCKER_USERNAME }}/$SERVERNAME 
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/$SERVERNAME:latest
