name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: CI Docker Login
      run: |
        docker login docker.com -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Build the Docker image（kubetools）
      run: |
        cd kubetools && docker build -t docker.com/corray/kubetools:$(date +%s) .
        docker push docker.com/corray/kubetools:$(date +%s)
